# Global rules
arrowParens: always
bracketSpacing: false
endOfLine: lf
printWidth: 80
quoteProps: consistent
singleQuote: false
tabWidth: 2
trailingComma: all

overrides:
  - files: "*.md"
    options:
      proseWrap: always
